version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: canoa_db
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data